openapi: 3.0.0
info:
  title: GovStack IM Service Metadata listClients API
  version: '0.3'
servers:
  - url: https://{securityserver}/r1
    variables:
      securityserver:
        default: SECURITYSERVER
        description: security server address
paths:
  /listClients:
    get:
      tags:
        - metaservices
      summary: List of Clients of GovStack
      operationId: listClients
      parameters:
        - name: instanceId
          required: false
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of Clients of GovStack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restClientDetailsListType'
components:
  schemas:
    restClientDetailsListType:
      type: object
      properties:
        member:
          type: array
          items:
            $ref: '#/components/schemas/restClientDetailsType'
    restClientDetailsType:
      type: object
      properties:
        objectType:
          type: object
          properties:
            object_type:
              type: string
              enum:
                - APPLICATION
                - MEMBER
                - SERVICE
        serviceType:
          type: string
        GovStackInstance:
          type: string
        memberClass:
          type: string
        memberCode:
          type: string
        applicationCode:
          type: string
        serviceCode:
          type: string
        serviceVersion:
          type: string
        endpointList:
          type: object
          properties:
            member:
              type: array
              items:
                $ref: '#/components/schemas/endpoint'
    endpoint:
      type: object
      properties:
        method:
          type: string
        path:
          type: string
